# Generated by Django 3.2.5 on 2021-07-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=7)),
                ('category', models.CharField(max_length=100)),
                ('price', models.FloatField(null=True)),
                ('nav', models.FloatField(null=True)),
                ('price_change', models.FloatField(null=True)),
                ('nav_change', models.FloatField(null=True)),
                ('price_minus_nav', models.FloatField(null=True)),
                ('current_discount', models.FloatField(null=True)),
                ('avg_52w', models.FloatField(null=True)),
                ('low_52w', models.FloatField(null=True)),
                ('high_52w', models.FloatField(null=True)),
                ('avg_minus_current', models.FloatField(null=True)),
                ('cents_to_avg', models.FloatField(null=True)),
                ('div', models.FloatField(null=True)),
                ('distribution_frequency', models.CharField(max_length=100)),
                ('current_yield', models.FloatField(null=True)),
                ('fiscal_year_end', models.CharField(max_length=50)),
                ('z_month_3', models.FloatField(null=True)),
                ('z_month_6', models.FloatField(null=True)),
                ('z_year', models.FloatField(null=True)),
                ('fund_sponsor', models.CharField(max_length=100)),
                ('last_updated', models.DateField()),
            ],
        ),
    ]
