# Generated by Django 3.2.5 on 2021-07-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cef', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cef',
            name='avg_52w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cef',
            name='avg_minus_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cef',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cef',
            name='cents_to_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cef',
            name='current_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cef',
            name='current_yield',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cef',
            name='distribution_frequency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cef',
            name='div',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cef',
            name='fiscal_year_end',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cef',
            name='fund_sponsor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cef',
            name='high_52w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cef',
            name='low_52w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cef',
            name='nav',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cef',
            name='nav_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cef',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cef',
            name='price_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cef',
            name='price_minus_nav',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cef',
            name='z_month_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cef',
            name='z_month_6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cef',
            name='z_year',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
