# Generated by Django 3.2.5 on 2021-10-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=4)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('nav', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('price_change', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nav_change', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('price_minus_nav', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('current_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('average_52w', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('low_52w', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('high_52w', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('average_minus_current', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cents_to_average', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distribution_frequency', models.CharField(blank=True, max_length=30, null=True)),
                ('current_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fiscal_year_end', models.CharField(blank=True, max_length=30, null=True)),
                ('z_score_3', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('z_score_6', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('z_score_12', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fund_sponsor', models.CharField(blank=True, max_length=40, null=True)),
                ('last_update', models.CharField(blank=True, max_length=100, null=True)),
                ('is_updated', models.BooleanField(default=False)),
            ],
        ),
    ]
